# Copyright 2026 Michael Pilosov. All rights reserved.
"""Package one published work as a BrightSign SD card root.

Copy the contents of the output folder onto the root of a FAT32/exFAT SD card.
The player runs autorun.brs, which opens the work full screen in an HTML widget.
"""
import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MARKER = '<script id="piece-config" type="application/json">'

AUTORUN = '''' Generated by scripts/brightsign.py for {slug}.
Sub Main()
    port = CreateObject("roMessagePort")
    mode = CreateObject("roVideoMode")
    rect = CreateObject("roRectangle", 0, 0, mode.GetResX(), mode.GetResY())
    ' websecurity off: module scripts and fetch() are blocked from file:// otherwise.
    config = {{
        url: "file:///sd:/index.html",
        javascript_enabled: true,
        mouse_enabled: {mouse},
        storage_path: "SD:/html-storage",
        storage_quota: 104857600,
        security_params: {{ websecurity: false }}{inspector}
    }}
    html = CreateObject("roHtmlWidget", rect, config)
    html.SetPort(port)
    html.Show()
    while true
        message = wait(0, port)
    end while
End Sub
'''


def embed(html, piece):
    start = html.index(MARKER) + len(MARKER)
    end = html.index('</script>', start)
    embedded = json.dumps(piece, separators=(',', ':')).replace('<', '\\u003c')
    return html[:start] + embedded + html[end:]


def build(slug, out, *, show_controls, touch, inspector):
    source = ROOT / 'site' / 'work' / slug
    if not (source / 'piece.json').is_file():
        raise SystemExit(f'site/work/{slug}/ is not a published work')
    if out.exists():
        if not (out / 'autorun.brs').is_file():
            raise SystemExit(f'{out} exists and is not a previous BrightSign build; refusing to replace it')
        shutil.rmtree(out)
    shutil.copytree(source, out)
    piece = json.loads((out / 'piece.json').read_text())
    piece['display'] = {**piece.get('display', {}), 'hideOverlay': not show_controls}
    (out / 'piece.json').write_text(json.dumps(piece, indent=2) + '\n')
    index = out / 'index.html'
    index.write_text(embed(index.read_text(), piece))
    (out / 'autorun.brs').write_text(AUTORUN.format(
        slug=slug, mouse='true' if touch else 'false',
        inspector=',\n        inspector_server: { port: 2999 }' if inspector else ''))
    return out


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('slug', help='published work under site/work/')
    parser.add_argument('-o', '--out', type=Path, help='output folder (default: brightsign/<slug>)')
    parser.add_argument('--show-controls', action='store_true', help='start with the control panel visible')
    parser.add_argument('--no-touch', dest='touch', action='store_false', help='ignore touch and mouse input')
    parser.add_argument('--inspector', action='store_true', help='expose Chrome DevTools on <player-ip>:2999')
    args = parser.parse_args()
    out = build(args.slug, args.out or ROOT / 'brightsign' / args.slug,
                show_controls=args.show_controls, touch=args.touch, inspector=args.inspector)
    print(f'Copy the contents of {out.relative_to(ROOT) if out.is_relative_to(ROOT) else out}/ to the SD card root.')
